### ISSUE TITLE
H2 DB size

### ISSUE THREAD

**Issue by PSLLSP** [signum-network/signum-node#601]
signum-node-v3.3.3.zip

I think that DB size doubled in v3.3.3.

My DB was created few weeks ago, I migrated it for v3.3.0 a week ago (renamed filenames). When I upgraded to v3.3.3, my DB with block-chain was corrupted and I downloaded block-chain from block 0. And I see difference. DB before corruption was synced and had size 5.9G, new database, created by v3.3.3, has size 14GB!

Fresh new DB, synced, 14GB:
```
$ du -sh db/; ll -h db/
14G	db/
total 14G
drwxrwxr-x  2  user user 4,0K Feb 11 22:15 ./
drwxrwxr-x 10  user user 4,0K Feb 11 22:26 ../
-rw-rw-r--  1  user user  14G Feb 14 11:57 signum.mv.db
-rw-rw-r--  1  user user 386K Feb 11 22:25 signum.trace.db
```

Corrupted DB, was synced, 5.9GB:
```
$ du -sh db0/; ll -h db0/
5,9G	db0/
total 5,9G
drwxr-xr-x  2 user user 4,0K Feb 11 18:14 ./
drwxrwxr-x 10 user user 4,0K Feb 11 22:26 ../
-rw-rw-r--  1 user user  64M Jan 31 03:04 burst.h2.trace.db
-rw-rw-r--  1 user user  67M Oct 20 18:50 burst.h2.trace.db.old
-rw-rw-r--  1 user user 5,7G Feb 10 00:15 signum.mv.db
-rw-rw-r--  1 user user  13M Feb 11 18:32 signum.trace.db
-rw-rw-r--  1 user user  70M Feb 11 18:14 signum.trace.db.old
```

I do not know why my DB was corrupted. One reason could be that PC was for some time with full disk (no free space left), other reason could be that I replaced `jar` file (v3.3.2->v3.3.3) while node was running and I forget to restart it for hour or two. Or any other reason, I just do not know. I open this issue to highlight, that DB size doubled. There is a chance, that DB was bigger in the past but corruption cut part of the DB file (because disk was full).

Anyway, I add here information, when DB was corrupted, I was not able to start v3.3.3:
```
$ java -jar signum-node.jar --headless
Feb 11, 2022 6:31:20 PM signum.Launcher main
INFO: Running in headless mode as specified by argument
Feb 11, 2022 6:31:20 PM brs.Burst loadProperties
INFO: Initializing Signum Node version v3.3.3
Feb 11, 2022 6:31:20 PM brs.Burst loadProperties
INFO: Configurations from folder ./conf
Feb 11, 2022 6:31:20 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[SEVERE] 2022-02-11 18:31:23 com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
        at org.h2.engine.Database.getPageStore(Database.java:2739)
        at org.h2.engine.Database.open(Database.java:769)
        at org.h2.engine.Database.openDatabase(Database.java:319)
        at org.h2.engine.Database.<init>(Database.java:313)
        at org.h2.engine.Engine.openSession(Engine.java:69)
        at org.h2.engine.Engine.openSession(Engine.java:201)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
        at org.h2.engine.Engine.createSession(Engine.java:161)
        at org.h2.engine.Engine.createSession(Engine.java:31)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
        at org.h2.Driver.connect(Driver.java:69)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at brs.db.sql.Db.init(Db.java:130)
        at brs.Burst.loadWallet(Burst.java:209)
        at brs.Burst.init(Burst.java:169)
        at brs.Burst.main(Burst.java:153)
        at signum.Launcher.main(Launcher.java:52)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 477841, expected page length 4..3072, got 0 [1.4.199/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Page.get(Page.java:221)
        at org.h2.mvstore.MVMap.get(MVMap.java:402)
        at org.h2.mvstore.MVMap.get(MVMap.java:389)
        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1088)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1025)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
        ... 26 more
[SEVERE] 2022-02-11 18:31:23 brs.Burst - com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
        at brs.db.sql.Db.init(Db.java:136)
        at brs.Burst.loadWallet(Burst.java:209)
        at brs.Burst.init(Burst.java:169)
        at brs.Burst.main(Burst.java:153)
        at signum.Launcher.main(Launcher.java:52)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at brs.db.sql.Db.init(Db.java:130)
        ... 4 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
        at org.h2.engine.Database.getPageStore(Database.java:2739)
        at org.h2.engine.Database.open(Database.java:769)
        at org.h2.engine.Database.openDatabase(Database.java:319)
        at org.h2.engine.Database.<init>(Database.java:313)
        at org.h2.engine.Engine.openSession(Engine.java:69)
        at org.h2.engine.Engine.openSession(Engine.java:201)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
        at org.h2.engine.Engine.createSession(Engine.java:161)
        at org.h2.engine.Engine.createSession(Engine.java:31)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
        at org.h2.Driver.connect(Driver.java:69)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        ... 7 more
Caused by: java.lang.IllegalStateException: File corrupted in chunk 477841, expected page length 4..3072, got 0 [1.4.199/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Page.get(Page.java:221)
        at org.h2.mvstore.MVMap.get(MVMap.java:402)
        at org.h2.mvstore.MVMap.get(MVMap.java:389)
        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1088)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1025)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
        ... 26 more
[INFO] 2022-02-11 18:31:23 brs.Burst - Shutting down...
Exception in thread "Thread-0" java.lang.NullPointerException
        at brs.db.sql.Db.shutdown(Db.java:171)
        at brs.Burst.shutdown(Burst.java:349)
        at brs.Burst.shutdown(Burst.java:312)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jjos2372** [comment]
Hello, please check this part of your config file:
```
## Make H2 database defrag and compact when shutting down.
## This is "off" by default as it can take 2 minutes
## but you really want this to be on after you are aware of this option

# Db.H2.DefragOnShutdown = off
```

Please remove the comment and turn it on, start your node and stop it with that option `on`, and check the sizes again.

**Comment by frankTheTank72** [comment]
@PSLLSP could you check the node with the Db.H2.DefragOnShutdown = on option ?

**Comment by rogerwim** [comment]
@PSLLSP 
> I changed configuration to `Db.H2.DefragOnShutdown = off` and started node again. Default value "off" makes sense...
no, you always want it on because it will grow with the chain and is needed to have it stay small

**Comment by jjos2372** [comment]
There is now an additional message when the 'defrag' starts, on the develop branch.
