### ISSUE TITLE
Exception in thread "Thread-3051" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by marssystems** [signum-network/signum-node#620]
I get this error when I close down the node (3.4.1) -

Exception in thread "Thread-3051" java.lang.ExceptionInInitializerError
	at brs.Burst.shutdown(Burst.java:368)
	at brs.BurstGUI.lambda$shutdown$1(BurstGUI.java:220)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: The function clCreateCommandQueueWithProperties is not supported
	at org.jocl.CL.clCreateCommandQueueWithPropertiesNative(Native Method)
	at org.jocl.CL.clCreateCommandQueueWithProperties(CL.java:5382)
	at brs.OCLPoC.<clinit>(OCLPoC.java:117)
	... 3 more

**Comment by frankTheTank72** [comment]
We have a new config which avoids a direct close  :

## Timeout in Seconds to wait for a graceful shutdown

node.shutdownTimeout = 60

I consider this as closed - please repon if still exists
