### ISSUE TITLE
What causes these Node errors, when this happens my BTDEX complains about something and cannot do a transaction.

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#664]
What causes these Node errors, when this happens my BTDEX complains about something and cannot do a transaction?

Usually when I see this, I shutdown Node and start it again.

`[INFO] 2022-09-17 07:00:59 brs.TransactionProcessorImpl - Error processing transaction
org.jooq.exception.DataAccessException: SQL [select (exists (select "transaction"."db_id", "transaction"."id", "transaction"."deadline", "transaction"."sender_public_key", "transaction"."recipient_id", "transaction"."amount", "transaction"."fee", "transaction"."height", "transaction"."block_id", "transaction"."signature", "transaction"."timestamp", "transaction"."type", "transaction"."subtype", "transaction"."sender_id", "transaction"."block_timestamp", "transaction"."full_hash", "transaction"."referenced_transaction_fullhash", "transaction"."attachment_bytes", "transaction"."version", "transaction"."has_message", "transaction"."has_encrypted_message", "transaction"."has_public_key_announcement", "transaction"."ec_block_height", "transaction"."ec_block_id", "transaction"."has_encrypttoself_message", "transaction"."cash_back_id" from "transaction" where "transaction"."id" = -1496101895890999077))]; General error: "java.lang.IllegalStateException: Reading from nio:C:/Users/pjb/Downloads/signum-node-v3.5.0-win_x64/db/signum.mv.db failed; file length -1 read length 768 at 4114108850 [1.4.199/1]"; SQL statement:
select (exists (select "transaction"."db_id", "transaction"."id", "transaction"."deadline", "transaction"."sender_public_key", "transaction"."recipient_id", "transaction"."amount", "transaction"."fee", "transaction"."height", "transaction"."block_id", "transaction"."signature", "transaction"."timestamp", "transaction"."type", "transaction"."subtype", "transaction"."sender_id", "transaction"."block_timestamp", "transaction"."full_hash", "transaction"."referenced_transaction_fullhash", "transaction"."attachment_bytes", "transaction"."version", "transaction"."has_message", "transaction"."has_encrypted_message", "transaction"."has_public_key_announcement", "transaction"."ec_block_height", "transaction"."ec_block_id", "transaction"."has_encrypttoself_message", "transaction"."cash_back_id" from "transaction" where "transaction"."id" = -1496101895890999077)) [50000-199]
	at org.jooq_3.15.7.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2997)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.impl.Tools.attach(Tools.java:1258)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4598)
	at org.jooq.impl.DefaultDSLContext.lambda$fetchValue$47(DefaultDSLContext.java:4618)
	at org.jooq.impl.Tools.attach(Tools.java:1258)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4618)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4628)
	at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4700)
	at brs.db.sql.SqlTransactionDb.lambda$hasTransaction$2(SqlTransactionDb.java:50)
	at brs.db.sql.Db.useDSLContext(Db.java:232)
	at brs.db.sql.SqlTransactionDb.hasTransaction(SqlTransactionDb.java:49)
	at brs.TransactionProcessorImpl.processTransactions(TransactionProcessorImpl.java:343)
	at brs.TransactionProcessorImpl.broadcast(TransactionProcessorImpl.java:215)
	at brs.http.BroadcastTransaction.processRequest(BroadcastTransaction.java:72)
	at brs.http.APIServlet$JsonRequestHandler.processRequest(APIServlet.java:198)
	at brs.http.APIServlet.process(APIServlet.java:341)
	at brs.http.APIServlet.doGet(APIServlet.java:272)
	at brs.http.APIServlet.doPost(APIServlet.java:281)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:483)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:332)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:711)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:418)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:675)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:410)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Reading from nio:C:/Users/pjb/Downloads/signum-node-v3.5.0-win_x64/db/signum.mv.db failed; file length -1 read length 768 at 4114108850 [1.4.199/1]"; SQL statement:
select (exists (select "transaction"."db_id", "transaction"."id", "transaction"."deadline", "transaction"."sender_public_key", "transaction"."recipient_id", "transaction"."amount", "transaction"."fee", "transaction"."height", "transaction"."block_id", "transaction"."signature", "transaction"."timestamp", "transaction"."type", "transaction"."subtype", "transaction"."sender_id", "transaction"."block_timestamp", "transaction"."full_hash", "transaction"."referenced_transaction_fullhash", "transaction"."attachment_bytes", "transaction"."version", "transaction"."has_message", "transaction"."has_encrypted_message", "transaction"."has_public_key_announcement", "transaction"."ec_block_height", "transaction"."ec_block_id", "transaction"."has_encrypttoself_message", "transaction"."cash_back_id" from "transaction" where "transaction"."id" = -1496101895890999077)) [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.command.Command.executeQuery(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
	at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4163)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	... 57 more
Caused by: java.lang.IllegalStateException: Reading from nio:C:/Users/pjb/Downloads/signum-node-v3.5.0-win_x64/db/signum.mv.db failed; file length -1 read length 768 at 4114108850 [1.4.199/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
	at org.h2.mvstore.Cursor.traverseDown(Cursor.java:165)
	at org.h2.mvstore.Cursor.<init>(Cursor.java:31)
	at org.h2.mvstore.tx.TransactionMap$TMIterator.<init>(TransactionMap.java:701)
	at org.h2.mvstore.tx.TransactionMap$KeyIterator.<init>(TransactionMap.java:652)
	at org.h2.mvstore.tx.TransactionMap.keyIterator(TransactionMap.java:575)
	at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:273)
	at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:266)
	at org.h2.index.BaseIndex.find(BaseIndex.java:132)
	at org.h2.index.IndexCursor.find(IndexCursor.java:163)
	at org.h2.table.TableFilter.next(TableFilter.java:475)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:742)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)
	at org.h2.command.dml.Query.query(Query.java:435)
	at org.h2.command.dml.Query.query(Query.java:397)
	at org.h2.expression.condition.ConditionExists.getValue(ConditionExists.java:33)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1890)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:742)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)
	at org.h2.command.dml.Query.query(Query.java:435)
	at org.h2.command.dml.Query.query(Query.java:397)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	... 66 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:406)
	... 100 more
`

**Comment by ohager** [comment]
This is an typical H2 issue. Running Main Net with H2 is not recommended anymore. We assume that the database file is too large for H2 to be handled correctly. An upgrade to newer version of H2 may be the fix. But I remember that @jjos2372 once trie to update to V2 but too many breaking changes,

**Comment by frankTheTank72** [comment]
yes we need to wait until H2 2.x version gets stable .. maybe we revisit this in the next months

**Comment by frankTheTank72** [comment]
I close the ticket as it is a known error by H2 - for now pls move to MySQL if possible
