### ISSUE TITLE
Uncaught exception in blockImporterThread while syncing blockchain

### ISSUE THREAD

**Issue by segfaultDelirium** [signum-network/signum-node#748]
I'm running signum node version 3.7.1 with mariadb. The blockchain is not yet synchronized (last block height is 333919) and while synchronizing i got a bunch of logs like below. Same logs are printed when I kill the process and start new one. 

[SEVERE] 2023-08-06 19:27:25 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `total_fee_cash_back`, `total_fee_burnt`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (-7600909391091829745, 3, 80770327, -7769745063026428976, 36446707232483, 2600000000, 0, 0, 4823, X'6079d6016564397525cf4865768b63807f00a7c5c7d18957fdfa5e2013237f2e', X'd0f3f6f207522c94f813f006f5a88040254ac004624020f6c94e06ab328b4742', X'2886dbf6e29cfed9', 906909, 333921, X'5bacd12a1d525c26eb2854938ca7b0f8f62068ad1aabc14ff27a667813adaa41', X'1277b1693fa57ef243dab0da4ded550e8c5619ed614a5e9e68301ee987e4db0e710fd6913c5bc0ed9167cee043556a7d08a5a056872750af5b73e4bcd716a22c', X'9a9ef1c81c34f60300a182cc31c06759638a3774fd9cd5c39996142d0032ec9b', -845331905997741554, 271256723, null)]; (conn=6503) Cannot add or update a child row: a foreign key constraint fails (`signum`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
        at org.jooq_3.15.7.MARIADB.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2997)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:111)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:130)
        at brs.db.sql.SqlBlockchainStore.lambda$addBlock$15(SqlBlockchainStore.java:295)
        at brs.db.sql.Db.useDSLContext(Db.java:236)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:294)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:845)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1051)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:641)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=6503) Cannot add or update a child row: a foreign key constraint fails (`signum`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:235)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:378)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:419)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:984)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
        ... 15 more
Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`signum`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
        ... 23 more

**Comment by frankTheTank72** [comment]
does it continue after you restart the node ?

**Comment by segfaultDelirium** [comment]
> does it continue after you restart the node ?

yes, after restarting the process it's the same error messages

**Comment by segfaultDelirium** [comment]
I was using the jar release on linux, maybe that's the cause.

**Comment by segfaultDelirium** [comment]
Yes, no error this time. I don't know what was wrong the previous time, but starting with fresh database and signum node jar worked.
