### ISSUE TITLE
[Error] Failed to parse block: SQL

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#759]
In v3.7.3, in Windows, after added the token ID 13240027460799312630), I started to get these error messages every 1 or 2 seconds:

[INFO] 2023-12-27 13:27:29 brs.BlockchainProcessorImpl - Failed to parse block: SQL [select (exists (select 1 "one" from "block" where "block"."id" = cast(? as bigint)))]; General error: "java.lang.IllegalStateException: Reading from nio:C:/signum-node-v3.7.3-win_x64/db/signum.mv.db failed; file length -1 read length 1024 at 14395672715 [1.4.199/1]"; SQL statement:
select (exists (select 1 "one" from "block" where "block"."id" = cast(? as bigint))) [50000-199]
[INFO] 2023-12-27 13:27:31 brs.BlockchainProcessorImpl - Failed to parse block: SQL [select (exists (select 1 "one" from "block" where "block"."id" = cast(? as bigint)))]; General error: "java.lang.IllegalStateException: Reading from nio:C:/signum-node-v3.7.3-win_x64/db/signum.mv.db failed; file length -1 read length 1024 at 14395672715 [1.4.199/1]"; SQL statement:
select (exists (select 1 "one" from "block" where "block"."id" = cast(? as bigint))) [50000-199]

**Comment by frankTheTank72** [comment]
Hi  - looks like you use H2 - a restart should solve the issue

**Comment by ohager** [comment]
NIO error is a known H2 error. We hope that with V2 we'll get rid of this error. #760

**Comment by ohager** [comment]
@josergc https://stackoverflow.com/questions/69576410/h2-intermittently-experiencing-a-stackoverflowerror-when-first-hitting-the-datab

**Comment by josergc** [comment]
yes, it's using H2. I couldn't verify if restarting the node the issue would be fixed because it started to print the messages posted at https://github.com/signum-network/signum-node/issues/750 while I was preparing this report. I had to terminate the process and restore the db from a previous backup to no download the whole chain.

**Comment by josergc** [comment]
just in case of it is related, previously to adding the abovementioned token, I did a multiout payment with my node, but the error at #750 did not appear immediately, then I continued browsing the transactions while I was waiting for the completion of the payment, and I added the token which led to the reported error in this issue

**Comment by ohager** [comment]
> just in case of it is related, previously to adding the abovementioned token, I did a multiout payment with my node, but the error at #750 did not appear immediately, then I continued browsing the transactions while I was waiting for the completion of the payment, and I added the token which led to the reported error in this issue

which version are you running? #750 should be fixed by 3.7.3

**Comment by josergc** [comment]
3.7.3

**Comment by josergc** [comment]
one more hint about this node, it is being used by an instance of [signum-pool](https://github.com/signum-network/signum-pool)

**Comment by ohager** [comment]
3.8 is in the baking. Release expected still this month

**Comment by ohager** [comment]
@josergc how is it with 3.8?

**Comment by josergc** [comment]
in the 3.8.0 with H2 v2, the node did not crash
![image](https://github.com/signum-network/signum-node/assets/7774952/c287e642-b184-46b3-9a40-1c7143d6e04b)

but I saw these messages in the console of the web browser and the pop-up window did not disappear
```
brs.assetexchange.js:669  Uncaught TypeError: BRS.accountInfo.assetBalances is not iterable
    at showHideBookmarkAllAssetsButton (brs.assetexchange.js:669:49)
    at BRS.loadAssetExchangeSidebar (brs.assetexchange.js:469:9)
    at BRS.pages.asset_exchange (brs.assetexchange.js:14:13)
    at BRS.logoSidebarClick (brs.js:449:32)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:41772)
    at y.handle (jquery.min.js:2:39791)
brs.assetexchange.js:669  Uncaught TypeError: BRS.accountInfo.assetBalances is not iterable
    at showHideBookmarkAllAssetsButton (brs.assetexchange.js:669:49)
    at BRS.loadAssetExchangeSidebar (brs.assetexchange.js:469:9)
    at BRS.goToAsset (brs.assetexchange.js:1785:17)
    at BRS.forms.addAssetBookmarkComplete (brs.assetexchange.js:244:17)
    at BRS.saveAssetBookmarks (brs.assetexchange.js:297:13)
    at BRS.forms.addAssetBookmark (brs.assetexchange.js:224:13)
    at BRS.submitForm (brs.forms.js:322:28)
    at HTMLButtonElement.<anonymous> (brs.eventlisteners.js:73:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:41772)
    at y.handle (jquery.min.js:2:39791)
```
![image](https://github.com/signum-network/signum-node/assets/7774952/da957d64-ab21-4521-83c4-5e82cedca7b3)

Trying to find if I can reproduce the issue reloading the GUI, I attempted to add it again, then a toast message in red appeared saying that the token is already added, but the pop-up did not go away and the buttons are in disabled state.
![image](https://github.com/signum-network/signum-node/assets/7774952/d9202d44-dc8a-4330-bc99-9c4818d01bda)

Then, I reloaded the GUI one more time, I removed the token, and with the network tab opened, I attempted to add the token again but this time it did it with success.
![image](https://github.com/signum-network/signum-node/assets/7774952/a0f7cbfe-fccc-4bd1-9589-a189123d6626)

So not sure if it only happens the first time.

**Comment by ohager** [comment]
the classic wallet error is client side, i.e. of the wallet itself and not the node. I consider this issue as solved. In the next upcoming version the classic wallet will be substituted by the modernized neo-classic wallet.
