### ISSUE TITLE
New docker pull eats ram.

### ISSUE THREAD

**Issue by thehatch2002** [signum-network/signum-node#772]
Ever since I updated the docker, this now eats 6gigs plus of my ram.  I have seen it hit 9 gigs.  May want to find out why it is doing this.

**Comment by ohager** [comment]
wow... that's a lot. What was it before? Which Version are you running now? Which Database? 
I'm not sure, if this is related to the node itself or something with Docker itself. 

I'm working on new docker images in general - independent of that. So, while I'm working on this I stay attentive.

Disclaimer: I'm no Docker expert... help from more experienced is welcome @damccull

**Comment by thehatch2002** [comment]
It used to be about 3 gigs or so.  After awhile I have to restart the docker to free up ram.

**Comment by damccull** [comment]
Have you changed docker images at all, or have you updated docker itself? What changes did you make before you noticed the increase?

Docker can be configured to restrict the ram it offers containers, and java tends to use a large amount of ram by default. I didn't place any ram restrictions on the java command running in the container because some folks might want a bunch of ram available. You can use docker to restrict the available memory when launching it from the cli or via docker compose.

CLI ([docs](https://docs.docker.com/config/containers/resource_constraints)):
```bash
docker run [...] --memory=3g [...]
```

Compose ([docs]()):
```
version: '3'
services:
    signum:
        deploy:
            resources:
                limits:
                    memory: 50M
    #...etc
```

**Comment by ohager** [comment]
@damccull @thehatch2002 That's a way we sh/could go: Limit the max RAM per container on cli side and then use e.g. `-XX:MaxRAMPercentage=90.0` option inside the container.

**Comment by damccull** [comment]
@thehatch2002 what database are you using?

@ohager didn't we have an H2 memory issue in the past too? There was something with one of our upgrades that H2 caused due to a bug in their release, and we got it on upgrade.

**Comment by thehatch2002** [comment]
> I don't know the real reason it's using so much ram. Maybe some code changes? It used to store a portion of the DB in memory as a cache, and it uses several threads to process changes. I haven't seen the code in over a year though, so maybe jjos has an answer?
> 
> Have you changed docker images at all, or have you updated docker itself? What changes did you make before you noticed the increase?
> 
> To work around,Docker can be configured to restrict the ram it offers containers, and java tends to use a large amount of ram by default. I didn't place any ram restrictions on the java command running in the container because some folks might want a bunch of ram available. You can use docker to restrict the available memory when launching it from the cli or via docker compose.
> 
> CLI ([docs](https://docs.docker.com/config/containers/resource_constraints)):
> 
> ```shell
> docker run [...] --memory=3g [...]
> ```
> 
> Compose (docs):
> 
> ```
> version: '3'
> services:
>     signum:
>         deploy:
>             resources:
>                 limits:
>                     memory: 50M
>     #...etc
> ```

Well I am using unraid, I am unsure how to change the memory settings as its all automated.

**Comment by thehatch2002** [comment]
> wow... that's a lot. What was it before? Which Version are you running now? Which Database? I'm not sure, if this is related to the node itself or something with Docker itself.
> 
> I'm working on new docker images in general - independent of that. So, while I'm working on this I stay attentive.
> 
> Disclaimer: I'm no Docker expert... help from more experienced is welcome @damccull

The docker image I am using is  signumnetwork/node:latest-h2

As far as the database, I just used the regular conf file with my node id in it.  I am not using maria.db or anything special.

**Comment by ohager** [comment]
@thehatch2002 could check the ram limiting feature for the docker image? Did it work for you. The only explanation for eating ram is that in 3.7.3 more indices were added and thus a significant sync speed up was achieved. Maybe there's a correlation.

**Comment by damccull** [comment]
Apparently there is a parameter you can set in your unpaid per container: `-memory=2G`. It's apparently in an advanced view you can activate on settings page.

> Well I am using unraid, I am unsure how to change the memory settings as its all automated.

**Comment by thehatch2002** [comment]
> Apparently there is a parameter you can set in your unpaid per container: `-memory=2G`. It's apparently in an advanced view you can activate on settings page.
> 
> > Well I am using unraid, I am unsure how to change the memory settings as its all automated.

I didn't know that.  what do i do just add -memory=3g next to the -- init?

**Comment by thehatch2002** [comment]
> Apparently there is a parameter you can set in your unpaid per container: `-memory=2G`. It's apparently in an advanced view you can activate on settings page.
> 
> > Well I am using unraid, I am unsure how to change the memory settings as its all automated.

Actually next to --init it failed, but i put it in the post section under it and it installed.  I'll see if it works?  hopefully i put that in the right place

**Comment by thehatch2002** [comment]
That is the database I am running.

🚀Starting Signum Node
[INFO] 2024-01-19 20:33:52 brs.db.sql.Db - Running flyway migration
[INFO] 2024-01-19 20:33:52 brs.db.sql.Db - Using SQL Backend with Dialect H2
[INFO] 2024-01-19 20:34:07 brs.BlockchainProcessorImpl - Genesis block already in database

**Comment by thehatch2002** [comment]
After using the --memory with 2 g...its now hovering around 1.581 to 1.59 gb  and going back in forth.  Seems to have resolved the issue.  If it crashes I'll be sure to post about it on here.   I never knew I could limit ram in dockers.  This is a game changer.

**Comment by damccull** [comment]
Glad to hear it's looking resolved. I don't know unraid at all but I know docker, and I know unraid uses docker under the hood so I just googled it. Will you please close your issue as solved? I'm not an admin here so can't do it.

**Comment by thehatch2002** [comment]
I spoken too soon.  The docker crash/closed.  I checked the logs and see this.

Jan 19, 2024 8:33:27 PM signum.Launcher main
INFO: Running in headless mode as specified by argument
Jan 19, 2024 8:33:27 PM brs.Burst loadProperties
INFO: Initializing Signum Node version v3.7.3
Jan 19, 2024 8:33:27 PM brs.Burst loadProperties
INFO: Configurations from folder ./conf
Jan 19, 2024 8:33:27 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-01-19 20:33:52 brs.db.sql.Db - Running flyway migration
[INFO] 2024-01-19 20:33:52 brs.db.sql.Db - Using SQL Backend with Dialect H2
[INFO] 2024-01-19 20:34:07 brs.BlockchainProcessorImpl - Genesis block already in database
[INFO] 2024-01-19 20:35:34 brs.BlockchainProcessorImpl - Last block height: 1233419, baseTarget: 2182806, averageCommitmentNQT 2007020994560
[INFO] 2024-01-19 20:35:48 brs.peer.Peers - P2P max connections: 20
[INFO] 2024-01-19 20:35:50 brs.peer.Peers - Attempting to map 174.104.6.177:8123 -> /10.46.1.61:8123 on Gateway Debian router (Debian router)
[INFO] 2024-01-19 20:35:50 brs.peer.Peers - UPnP Mapping successful
[INFO] 2024-01-19 20:35:50 brs.peer.GetNextBlocks - P2P max number of blocks: 720
[SEVERE] 2024-01-19 20:35:51 brs.peer.Peers - Failed to start peer networking server
java.io.IOException: Failed to bind to /0.0.0.0:8123
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
        at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:401)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.eclipse.jetty.server.Server.doStart(Server.java:397)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at brs.peer.Peers$Init.lambda$init$1(Peers.java:381)
        at brs.util.ThreadPool.lambda$runAll$2(ThreadPool.java:163)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340)
        ... 17 more
Exception in thread "Thread-5" java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8123
        at brs.peer.Peers$Init.lambda$init$1(Peers.java:386)
        at brs.util.ThreadPool.lambda$runAll$2(ThreadPool.java:163)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:8123
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
        at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:401)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.eclipse.jetty.server.Server.doStart(Server.java:397)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at brs.peer.Peers$Init.lambda$init$1(Peers.java:381)
        ... 2 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340)
        ... 17 more
[INFO] 2024-01-19 20:35:52 brs.http.API - Started API server at 0.0.0.0:8125
[SEVERE] 2024-01-19 20:35:52 brs.Burst - Errors running startup tasks:
java.io.IOException: Failed to bind to /0.0.0.0:8123

java.lang.RuntimeException: Errors running startup tasks:
java.io.IOException: Failed to bind to /0.0.0.0:8123

        at brs.util.ThreadPool.runAll(ThreadPool.java:181)
        at brs.util.ThreadPool.start(ThreadPool.java:88)
        at brs.Burst.loadWallet(Burst.java:298)
        at brs.Burst.init(Burst.java:182)
        at brs.Burst.main(Burst.java:166)
        at signum.Launcher.main(Launcher.java:52)
[INFO] 2024-01-19 20:35:52 brs.Burst - Shutting down...
[INFO] 2024-01-19 20:35:52 brs.Burst - Do not force exit or kill the node process.
[INFO] 2024-01-19 20:35:52 brs.peer.Peers - 
[INFO] 2024-01-19 20:35:52 brs.db.sql.Db - H2 defragmentation started, this can take a while
🚀Starting Signum Node

** Press ANY KEY to close this window ** 


   I don't think the memory issue is releaded to the binding.  As far as I know, everything works given the binding error.

**Comment by damccull** [comment]
You're correct and that that is not a memory issue. It's trying to bind to a port that is already in use. Ensure that your previous instance of the container has shut down properly before you restart. Look through your existing network connections that are listening on the system and make sure you're not using that port on any other active containers.

**Comment by thehatch2002** [comment]
> You're correct and that that is not a memory issue. It's trying to bind to a port that is already in use. Ensure that your previous instance of the container has shut down properly before you restart. Look through your existing network connections that are listening on the system and make sure you're not using that port on any other active containers.

   You know what..I think that port resolved my issue. I'll keep you updated.  I think java ate the ram not signum.  I never seen the signum multiverse in the log before.  It was home assistant running.  I killed it and freed that port up. I must of had home assistant bridged or something in the past. 

🚀Starting Signum Node
Jan 19, 2024 9:22:55 PM signum.Launcher main
INFO: Running in headless mode as specified by argument
Jan 19, 2024 9:22:56 PM brs.Burst loadProperties
INFO: Initializing Signum Node version v3.7.3
Jan 19, 2024 9:22:56 PM brs.Burst loadProperties
INFO: Configurations from folder ./conf
Jan 19, 2024 9:22:56 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-01-19 21:23:58 brs.db.sql.Db - Running flyway migration
[INFO] 2024-01-19 21:23:59 brs.db.sql.Db - Using SQL Backend with Dialect H2
[INFO] 2024-01-19 21:24:03 brs.BlockchainProcessorImpl - Genesis block already in database
[INFO] 2024-01-19 21:24:22 brs.BlockchainProcessorImpl - Last block height: 1233419, baseTarget: 2182806, averageCommitmentNQT 2007020994560
[INFO] 2024-01-19 21:24:35 brs.peer.Peers - P2P max connections: 20
[INFO] 2024-01-19 21:24:37 brs.peer.Peers - Attempting to map xxxxxx:8123 -> /10.46.1.61:8123 on Gateway Debian router (Debian router)
[INFO] 2024-01-19 21:24:37 brs.peer.Peers - UPnP Mapping successful
[INFO] 2024-01-19 21:24:37 brs.peer.GetNextBlocks - P2P max number of blocks: 720
[INFO] 2024-01-19 21:24:38 brs.http.API - Started API server at 0.0.0.0:8125
[INFO] 2024-01-19 21:24:38 brs.peer.Peers - Started peer networking server at 0.0.0.0:8123
[INFO] 2024-01-19 21:24:38 brs.util.ThreadPool - Using 1 cores
[INFO] 2024-01-19 21:24:38 brs.Burst - Initialization took 101257 ms
[INFO] 2024-01-19 21:24:38 brs.Burst - Signum Multiverse v3.7.3 started successfully.
[INFO] 2024-01-19 21:24:38 brs.Burst - Running network: Signum

**Comment by thehatch2002** [comment]
So here is a follow up.  It is fixed.  It was apparently java eating that ram up from the port issue.  Glad you all pointed me to the memory restrictions...cus I like to save my 43 gigs of ram for other things...diff life saver even though that wasn't a fix lol.

**Comment by ohager** [comment]
great. glad to hear - closing
