### ISSUE TITLE
Error after upgrading to version 3.8.0

### ISSUE THREAD

**Issue by Antoninich** [signum-network/signum-node#775]
I have a problem after upgrading to 3.8.0.

```
signumnode02:~# java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Debian-1deb11u1, mixed mode, sharing)
```
```
signumnode02:~# mariadb --version
mariadb  Ver 15.1 Distrib 10.5.19-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```
```
янв 18 01:25:04 signumnode02 systemd[1]: Started Signum Node.                                                                                                                                                      
янв 18 01:25:05 signumnode02 java[3931681]: янв. 18, 2024 1:25:04 AM signum.Launcher main                                                                                                                          
янв 18 01:25:05 signumnode02 java[3931681]: INFO: Running in headless mode as specified by argument                                                                                                                
янв 18 01:25:05 signumnode02 java[3931681]: янв. 18, 2024 1:25:05 AM brs.Burst loadProperties                                                                                                                      
янв 18 01:25:05 signumnode02 java[3931681]: INFO: Initializing Signum Node version v3.8.0                                                                                                                          
янв 18 01:25:05 signumnode02 java[3931681]: янв. 18, 2024 1:25:05 AM brs.Burst loadProperties                                                                                                                      
янв 18 01:25:05 signumnode02 java[3931681]: INFO: Configurations from folder ./conf                                                                                                                                
янв 18 01:25:05 signumnode02 java[3931681]: янв. 18, 2024 1:25:05 AM brs.util.LoggerConfigurator init                                                                                                              
янв 18 01:25:05 signumnode02 java[3931681]: INFO: Custom user logging.properties not loaded                                                                                                                        
янв 18 01:25:05 signumnode02 java[3931681]: [INFO] 2024-01-18 01:25:05 brs.db.sql.Db - Running flyway migration                                                                                                    
янв 18 01:25:05 signumnode02 java[3931681]: [INFO] 2024-01-18 01:25:05 brs.db.sql.Db - Using SQL Backend with Dialect MariaDB - Version 10.5.19-MariaDB-0+deb11u2                                                  
янв 18 01:25:05 signumnode02 java[3931681]: [SEVERE] 2024-01-18 01:25:05 brs.Burst - SQL [select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`al
ias_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows
 only]; (conn=236959) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1                   
янв 18 01:25:05 signumnode02 java[3931681]: org.jooq.exception.DataAccessException: SQL [select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`ali
as_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows 
only]; (conn=236959) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1                    
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq_3.16.23.MARIADB.debug(Unknown Source)                                                                                                              
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.Tools.translate(Tools.java:3130)                                                                                                              
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)                                                                            
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)                                                                                                 
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)                                                                                   
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)                                                                     
янв 18 01:25:05 signumnode02 java[3931681]:         at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.db.sql.EntitySqlTable.get(EntitySqlTable.java:151)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.db.sql.EntitySqlTable.lambda$getBy$2(EntitySqlTable.java:118)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.db.sql.Db.useDSLContext(Db.java:215)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.db.sql.EntitySqlTable.getBy(EntitySqlTable.java:109)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.db.sql.SqlAliasStore.getTLD(SqlAliasStore.java:181)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.services.impl.AliasServiceImpl.addDefaultTLDs(AliasServiceImpl.java:69)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.Burst.loadWallet(Burst.java:238)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.Burst.init(Burst.java:185)
янв 18 01:25:05 signumnode02 java[3931681]:         at brs.Burst.main(Burst.java:169)
янв 18 01:25:05 signumnode02 java[3931681]:         at signum.Launcher.main(Launcher.java:52)
янв 18 01:25:05 signumnode02 java[3931681]: Caused by: java.sql.SQLSyntaxErrorException: (conn=236959) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
янв 18 01:25:05 signumnode02 java[3931681]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
янв 18 01:25:05 signumnode02 java[3931681]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
янв 18 01:25:05 signumnode02 java[3931681]:         at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:378)
янв 18 01:25:17 signumnode02 java[3931738]:         at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
янв 18 01:25:17 signumnode02 java[3931738]:         at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4408)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
янв 18 01:25:17 signumnode02 java[3931738]:         ... 13 more
янв 18 01:25:17 signumnode02 java[3931738]: Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
янв 18 01:25:17 signumnode02 java[3931738]: Query is: select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`alias_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows only
янв 18 01:25:17 signumnode02 java[3931738]: java thread: main
янв 18 01:25:17 signumnode02 java[3931738]:         at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:233)
янв 18 01:25:17 signumnode02 java[3931738]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
янв 18 01:25:17 signumnode02 java[3931738]:         ... 21 more

```

**Comment by Antoninich** [comment]
```
signumnode02:~# java --version
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Debian-1deb11u1, mixed mode, sharing)
```

**Comment by frankTheTank72** [comment]
You need mariaDB 10.6 version as minimum

**Comment by Antoninich** [comment]
Thanks. I have added a PR describing the minimum required version of MariaDB in README.md https://github.com/signum-network/signum-node/pull/776
