### ISSUE TITLE
Another database connection has already written to the database (database is locked)

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#820]
Using v3.8.1 in production, synchronizing from scratch, using SQLite with WAL support:

```
DB.Url=jdbc:sqlite:file:./db/signum.sqlite.db
DB.Username=
DB.Password=
DB.Optimize=true
DB.SqliteJournalMode = WAL
```

The full message:

```
[INFO] 2024-05-09 20:45:33 brs.statistics.StatisticsManagerImpl - handling 4.72 blocks/s account_balance cache hit ratio now/total:99.45%/99.46% account cache hit ratio now/total:99.42%/99.29%
org.jooq.exception.DataAccessException: SQL [update account set latest = 0 where (account.id = -6214514366495862188 and account.latest = 1)]; batch entry 0: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.jooq_3.16.23.SQLITE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3130)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:148)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:90)
	at org.jooq.impl.BatchSingle.executeStatic(BatchSingle.java:280)
	at org.jooq.impl.BatchSingle.execute(BatchSingle.java:174)
	at brs.db.sql.VersionedBatchEntitySqlTable.lambda$finish$0(VersionedBatchEntitySqlTable.java:96)
	at brs.db.sql.Db.useDSLContext(Db.java:132)
	at brs.db.sql.VersionedBatchEntitySqlTable.finish(VersionedBatchEntitySqlTable.java:79)
	at brs.services.impl.AccountServiceImpl.flushAccountTable(AccountServiceImpl.java:156)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1144)
	at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.BatchUpdateException: batch entry 0: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:245)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:225)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:122)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:122)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:129)
	... 16 more
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:242)
	... 22 more
[SEVERE] 2024-05-09 20:46:12 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [update account set latest = 0 where (account.id = -6214514366495862188 and account.latest = 1)]; batch entry 0: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.jooq_3.16.23.SQLITE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3130)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:148)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:90)
	at org.jooq.impl.BatchSingle.executeStatic(BatchSingle.java:280)
	at org.jooq.impl.BatchSingle.execute(BatchSingle.java:174)
	at brs.db.sql.VersionedBatchEntitySqlTable.lambda$finish$0(VersionedBatchEntitySqlTable.java:96)
	at brs.db.sql.Db.useDSLContext(Db.java:132)
	at brs.db.sql.VersionedBatchEntitySqlTable.finish(VersionedBatchEntitySqlTable.java:79)
	at brs.services.impl.AccountServiceImpl.flushAccountTable(AccountServiceImpl.java:156)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1144)
	at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.BatchUpdateException: batch entry 0: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:245)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:225)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:122)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:122)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:129)
	... 16 more
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY_SNAPSHOT] Another database connection has already written to the database (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:242)
	... 22 more
```
![image](https://github.com/signum-network/signum-node/assets/7774952/f7535720-1a7e-4a7a-91ec-6b699a890997)

It seems that is able to recover by itself and continues, but I've got the computer like hang a couple of times already, so wondering if it is possible that if the node cannot recover from this, can it enter in an infinite loop that uses too much CPU causing the hang? I'll try to get more logs if it happens again.

Thank you in advance!!

**Comment by ipr0310** [comment]
I also faced this warning, this is expected:
https://github.com/signum-network/signum-node/blob/main/DB_SETUP_SQLITE.md#important-notes
