### ISSUE TITLE
SQLite exceptions, DB is locked

### ISSUE THREAD

**Issue by PSLLSP** [signum-network/signum-node#823]
Signum Node 3.8.1
Ubuntu Linux 18.04.6, amd64
openjdk version "17.0.7" 2023-04-18

I started node 13.8.1 with SQLite, just basic config.

conf/node.properties:

```
$ grep "^DB" conf/node.properties
DB.Url=jdbc:sqlite:file:./db/signum.sqlite.db
DB.SqliteJournalMode = WAL
```

```
$ diff -u conf/node-default.properties conf/node.properties 
--- conf/node-default.properties        2024-05-05 18:22:56.000000000 +0200
+++ conf/node.properties        2024-05-14 02:53:40.394147562 +0200
@@ -34,6 +34,7 @@
 # DB.Url=jdbc:h2:file:./db/signum-v2;DB_CLOSE_ON_EXIT=FALSE
 # DB.Username=
 # DB.Password=
+DB.Url=jdbc:sqlite:file:./db/signum.sqlite.db
 
 ## If you want to use MariaDB:
 
@@ -312,7 +313,7 @@
 ## WAL may occupy up to twice more disc space than others while running the node, but allows read concurrency and usually better performance (see more here: https://www.sqlite.org/wal.html)
 ## It's highly recommended to use WAL mode during syncing, to dramatically reduce I/O operations and though faster sync times.
 ## Info: MEMORY journal mode is not supported
-# DB.SqliteJournalMode = WAL
+DB.SqliteJournalMode = WAL
 
 ## Enable trimming of derived objects tables.
```

It is sync from block 0. Just few seconds after start I see exception (**DB is locked**):

```
May 14, 2024 2:54:31 AM signum.Launcher main
INFO: Running in headless mode as specified by argument
May 14, 2024 2:54:31 AM brs.Signum loadProperties
INFO: Initializing Signum Node version v3.8.1
May 14, 2024 2:54:31 AM brs.Signum loadProperties
INFO: Configurations from folder ./conf
May 14, 2024 2:54:31 AM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-05-14 02:54:33 brs.db.sql.Db - Using SQL Backend with Dialect SQLite - Version 3.45.2 (EXPERIMENTAL)
[INFO] 2024-05-14 02:54:33 brs.db.sql.Db - Running flyway migration
[INFO] 2024-05-14 02:54:33 brs.db.sql.dialects.DatabaseInstanceSqlite - SQLite optimization started...
[INFO] 2024-05-14 02:54:33 brs.db.sql.dialects.DatabaseInstanceSqlite - SQLite VACUUM started, this can take a while
[INFO] 2024-05-14 02:54:35 brs.BlockchainProcessorImpl - Genesis block not in database, starting from scratch
[INFO] 2024-05-14 02:54:35 brs.peer.Peers - P2P max connections: 20
[WARNING] 2024-05-14 02:54:41 brs.peer.Peers - Tried to establish UPnP, but it was denied by the network.
...
[INFO] 2024-05-14 02:55:44 brs.statistics.StatisticsManagerImpl - handling 55.56 blocks/s account_balance cache hit ratio now/total:99.52%/98.88% account cache hit ratio now/total:99.36%/98.40%
org.jooq.exception.DataAccessException: SQL [insert into block (id, version, timestamp, previous_block_id, total_amount, total_fee, total_fee_cash_back, total_fee_burnt, payload_length, generator_public_key, previous_block_hash, cumulative_difficulty, base_target, height, generation_signature, block_signature, payload_hash, generator_id, nonce, ats) values (-7926649096185958333, 3, 1482220, 5659549672795422904, 0, 0, 0, 0, 0, X'7F09F66C1586C75DFB700B043F0E4DF4D236877BFD6DA90BBE0F83621D580D19', X'B840A61B71C28A4EA01501A294F6FEB5014B12415D8D3FFEC4791AB13D6B9BE3', X'07010540039AC2', 20898016, 5966, X'3AA8EC1D86E49E8BC3ACDC7CEB8FF933893AF71660DF38570C84621142460E1B', X'66571450F938D50DFD123A8EBEA161A1300DCCBD62FF29669CDE95DE8495ED0206F30036EE76D0A009FD8EE6503EA526286AEABDED58CEA1ABEB136A93655695', X'E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855', -1270193065122712945, 44403978, null)]; [SQLITE_BUSY] The database file is locked (database is locked)
        at org.jooq_3.16.23.SQLITE.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3130)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:138)
        at brs.db.sql.SqlBlockchainStore.lambda$addBlock$17(SqlBlockchainStore.java:414)
        at brs.db.sql.Db.useDSLContext(Db.java:132)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:413)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:906)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1145)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.execute(DB.java:985)
        at org.sqlite.core.CoreStatement.exec(CoreStatement.java:91)
        at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:55)
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:43)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:428)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:961)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
        ... 15 more

[SEVERE] 2024-05-14 02:55:54 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into block (id, version, timestamp, previous_block_id, total_amount, total_fee, total_fee_cash_back, total_fee_burnt, payload_length, generator_public_key, previous_block_hash, cumulative_difficulty, base_target, height, generation_signature, block_signature, payload_hash, generator_id, nonce, ats) values (-7926649096185958333, 3, 1482220, 5659549672795422904, 0, 0, 0, 0, 0, X'7F09F66C1586C75DFB700B043F0E4DF4D236877BFD6DA90BBE0F83621D580D19', X'B840A61B71C28A4EA01501A294F6FEB5014B12415D8D3FFEC4791AB13D6B9BE3', X'07010540039AC2', 20898016, 5966, X'3AA8EC1D86E49E8BC3ACDC7CEB8FF933893AF71660DF38570C84621142460E1B', X'66571450F938D50DFD123A8EBEA161A1300DCCBD62FF29669CDE95DE8495ED0206F30036EE76D0A009FD8EE6503EA526286AEABDED58CEA1ABEB136A93655695', X'E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855', -1270193065122712945, 44403978, null)]; [SQLITE_BUSY] The database file is locked (database is locked)
        at org.jooq_3.16.23.SQLITE.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3130)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:138)
        at brs.db.sql.SqlBlockchainStore.lambda$addBlock$17(SqlBlockchainStore.java:414)
        at brs.db.sql.Db.useDSLContext(Db.java:132)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:413)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:906)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1145)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.execute(DB.java:985)
        at org.sqlite.core.CoreStatement.exec(CoreStatement.java:91)
        at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:55)
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:43)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:428)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:961)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
        ... 15 more
[INFO] 2024-05-14 02:55:55 brs.statistics.StatisticsManagerImpl - handling 41.67 blocks/s account_balance cache hit ratio now/total:99.56%/99.00% account cache hit ratio now/total:99.39%/98.57%
[INFO] 2024-05-14 02:56:18 brs.statistics.StatisticsManagerImpl - handling 21.74 blocks/s account_balance cache hit ratio now/total:99.55%/99.12% account cache hit ratio now/total:99.44%/98.73%
[INFO] 2024-05-14 02:56:35 brs.statistics.StatisticsManagerImpl - handling 31.25 blocks/s account_balance cache hit ratio now/total:99.75%/99.26% account cache hit ratio now/total:99.64%/98.92%
[INFO] 2024-05-14 02:56:54 brs.statistics.StatisticsManagerImpl - handling 25.00 blocks/s account_balance cache hit ratio now/total:99.72%/99.35% account cache hit ratio now/total:99.66%/99.07%
[INFO] 2024-05-14 02:57:15 brs.statistics.StatisticsManagerImpl - handling 25.00 blocks/s account_balance cache hit ratio now/total:99.58%/99.39% account cache hit ratio now/total:99.52%/99.14%
```

```
$ java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu118.04, mixed mode, sharing)
```

**Comment by frankTheTank72** [comment]
This can happen - check here https://github.com/signum-network/signum-node/blob/main/DB_SETUP_SQLITE.md#sqlite_busy-errors-while-syncing
