### ISSUE TITLE
v3.8.1, v3.8.2, SQLite; DB is inconsistent

### ISSUE THREAD

**Issue by PSLLSP** [signum-network/signum-node#824]
v3.8.1

I tried to sync from block 0. After about a day I see errors that DB is inconsistent. I have simple setup, I reported details in issue #823 that was already closed.

This issue could be a duplicate to #821...

```
$ du -sh db/
4.8G    db/

$ ls -l db/
total 4940436
drwxrwxr-x 2 user user       4096 May 14 02:54 ./
drwxrwxr-x 5 user user       4096 May 14 02:54 ../
-rw-rw-r-- 1 user user 4933681152 May 14 22:59 signum.sqlite.db
-rw-rw-r-- 1 user user     262144 May 14 22:58 signum.sqlite.db-shm
-rw-rw-r-- 1 user user  124774232 May 14 22:59 signum.sqlite.db-wal
```

Console with errors:

```
...
WARNING] 2024-05-14 22:41:38 brs.BlockchainProcessorImpl - Auto popping off as failed to push block
[WARNING] 2024-05-14 22:41:38 brs.BlockchainProcessorImpl - Popping off 243 blocks due to previous failures to push this block
[INFO] 2024-05-14 22:41:38 brs.BlockchainProcessorImpl - Rollback from 672382 to 672139
[WARNING] 2024-05-14 22:41:39 brs.BlockchainProcessorImpl - Block height 672139, total mined 207088570000000000, total effective
+burnt 207088556799981112
[WARNING] 2024-05-14 22:41:39 brs.BlockchainProcessorImpl - Database is inconsistent, try to pop off to block height 669600 or s
ync from empty.
[INFO] 2024-05-14 22:41:44 brs.BlockchainProcessorImpl - Error: lastBlock is null
[INFO] 2024-05-14 22:41:52 brs.statistics.StatisticsManagerImpl - handling 11.36 blocks/s account_balance cache hit ratio now/total:91.83%/97.29% account cache hit ratio now/total:92.99%/97.42%
[SEVERE] 2024-05-14 22:41:52 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Transaction not accepted: 18375910234290820363 transaction: {"type":0,"subtype":0,"timestamp":162616961,"deadline":1440,"senderPublicKey":"b8a83f749be6e0c5bd6205118edb3bbd71f14a55bcdd5977566821dedaac5030","recipient":"13383190289605706987","amountNQT":70383121760,"feeNQT":1470000,"ecBlockHeight":672374,"ecBlockId":"1014574692688231313","cashBackId":"0","signature":"d32c27f194a56bd485d08b4c55920455759fae984ec8b1005724c1b6633e8e0795afe27ab08db905f6de51265b12dfd1d1cfaa4a9a9d5269886a9919d46a00f9","attachment":{"version.Message":1,"message":"b6c444564ab64cc18a082bfa4e77a815f02b203906ad458da680ef4ab93c6cb4","messageIsText":true},"version":1}
        at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1195)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1150)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[SEVERE] 2024-05-14 22:41:52 brs.peer.PeerImpl - Reason for following blacklist: Transaction not accepted: 18375910234290820363 transaction: {"type":0,"subtype":0,"timestamp":162616961,"deadline":1440,"senderPublicKey":"b8a83f749be6e0c5bd6205118edb3bbd71f14a55bcdd5977566821dedaac5030","recipient":"13383190289605706987","amountNQT":70383121760,"feeNQT":1470000,"ecBlockHeight":672374,"ecBlockId":"1014574692688231313","cashBackId":"0","signature":"d32c27f194a56bd485d08b4c55920455759fae984ec8b1005724c1b6633e8e0795afe27ab08db905f6de51265b12dfd1d1cfaa4a9a9d5269886a9919d46a00f9","attachment":{"version.Message":1,"message":"b6c444564ab64cc18a082bfa4e77a815f02b203906ad458da680ef4ab93c6cb4","messageIsText":true},"version":1}
[INFO] 2024-05-14 22:41:52 brs.peer.PeerImpl - Blacklisting 213.221.57.86 (v3.8.0) because of: found invalid pull/push data during importing the block
[WARNING] 2024-05-14 22:41:52 brs.BlockchainProcessorImpl - Auto popping off as failed to push block
[WARNING] 2024-05-14 22:41:52 brs.BlockchainProcessorImpl - Popping off 244 blocks due to previous failures to push this block
[INFO] 2024-05-14 22:41:52 brs.BlockchainProcessorImpl - Rollback from 672382 to 672138
[WARNING] 2024-05-14 22:41:54 brs.BlockchainProcessorImpl - Block height 672138, total mined 207088528500000000, total effective+burnt 207088515299981112
[WARNING] 2024-05-14 22:41:54 brs.BlockchainProcessorImpl - Database is inconsistent, try to pop off to block height 669600 or sync from empty.
...
```

Few hours later:

```
...
[INFO] 2024-05-15 05:05:25 brs.BlockchainProcessorImpl - Error in blockchain download thread
java.lang.NullPointerException
[INFO] 2024-05-15 05:05:25 brs.BlockchainProcessorImpl - Error in blockchain download thread
java.lang.NullPointerException
...
```

**Comment by ohager** [comment]
Can you reproduce the error? Did you try a second or third time?

**Comment by PSLLSP** [comment]
I tried with Signum v 3.8.2 and I still see the issue. I cannot sync the node.

Linux Mint 21.3, amd64

```
$ java -version
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

$ sqlite3 --version
3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1
```
I synced from block 0 and I reached height 683953 and I see errors about DB inconsistency in the console:

```
Jul 24, 2024 12:48:33 PM signum.Launcher main
INFO: Running in headless mode as specified by argument
Jul 24, 2024 12:48:33 PM brs.Signum loadProperties
INFO: Initializing Signum Node version v3.8.2
Jul 24, 2024 12:48:33 PM brs.Signum loadProperties
INFO: Configurations from folder ./conf
Jul 24, 2024 12:48:33 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-07-24 12:48:36 brs.db.sql.Db - Using SQL Backend with Dialect SQLite - Version 3.45.2 (EXPERIMENTAL)
[INFO] 2024-07-24 12:48:36 brs.db.sql.Db - Running flyway migration
[INFO] 2024-07-24 12:48:37 brs.db.sql.dialects.DatabaseInstanceSqlite - SQLite optimization started...
[INFO] 2024-07-24 12:48:37 brs.db.sql.dialects.DatabaseInstanceSqlite - SQLite VACUUM started, this can take a while
[INFO] 2024-07-24 12:48:39 brs.BlockchainProcessorImpl - Genesis block not in database, starting from scratch
[INFO] 2024-07-24 12:48:39 brs.peer.Peers - P2P max connections: 20
[WARNING] 2024-07-24 12:48:45 brs.peer.Peers - Tried to establish UPnP, but it was denied by the network.
[INFO] 2024-07-24 12:48:46 brs.peer.GetNextBlocks - P2P max number of blocks: 720
[INFO] 2024-07-24 12:48:46 brs.web.server.ServerConnectorHttpBuilderImpl - HTTP API server enabled for 127.0.0.1:8125
[INFO] 2024-07-24 12:48:46 brs.web.server.ServerConnectorWebsocketBuilderImpl - [Experimental] WebSockets server enabled for 127.0.0.1:8126
[INFO] 2024-07-24 12:48:46 brs.web.server.WebServerImpl - API docs enabled
[INFO] 2024-07-24 12:48:47 brs.peer.Peers - Started peer networking server at 0.0.0.0:8123
[INFO] 2024-07-24 12:48:47 brs.web.server.WebServerImpl - Web Server started successfully
[INFO] 2024-07-24 12:48:47 brs.util.ThreadPool - Using 2 cores
[INFO] 2024-07-24 12:48:47 brs.Signum - Initialization took 13681 ms
[INFO] 2024-07-24 12:48:47 brs.Signum - Signum Multiverse v3.8.2 started successfully.
[INFO] 2024-07-24 12:48:47 brs.Signum - Running network: Signum
[INFO] 2024-07-24 12:49:02 brs.peer.Peers - Finished connecting to 3 well known peers.
...
[INFO] 2024-07-25 00:19:31 brs.peer.PeerImpl - Blacklisting 107.189.7.38 (v3.8.0) because of: found invalid pull/push data during importing the block
[WARNING] 2024-07-25 00:19:31 brs.BlockchainProcessorImpl - Auto popping off as failed to push block
[WARNING] 2024-07-25 00:19:31 brs.BlockchainProcessorImpl - Popping off 35 blocks due to previous failures to push this block
[INFO] 2024-07-25 00:19:31 brs.BlockchainProcessorImpl - Rollback from 683989 to 683954
[WARNING] 2024-07-25 00:19:31 brs.BlockchainProcessorImpl - Block height 683954, total mined 207571427000000000, total effective+burnt 207571426999981685
[WARNING] 2024-07-25 00:19:31 brs.BlockchainProcessorImpl - Database is inconsistent, try to pop off to block height 682514 or sync from empty.
[INFO] 2024-07-25 00:19:32 brs.BlockchainProcessorImpl - Error: lastBlock is null
[SEVERE] 2024-07-25 00:19:37 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Transaction not accepted: 418987173499205375 transaction: {"type":0,"subtype":0,"timestamp":165423139,"deadline":1440,"senderPublicKey":"b087915478ba8f3e53400f05ca73cf99ae36865a08f22cfd47de7b526ee0fe5b","recipient":"2945594293674691670","amountNQT":2904063250001,"feeNQT":36750000,"ecBlockHeight":683976,"ecBlockId":"8103454603351769933","cashBackId":"0","signature":"44160a321f5c30612d9032dec10bee9660f80c546495d230209d2744fd47fa01e40d3e0782fc787d01c16540f8bdcd1934235830358b89d14f33b528b4a892dd","attachment":{},"version":1}
        at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1195)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1150)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[SEVERE] 2024-07-25 00:19:37 brs.peer.PeerImpl - Reason for following blacklist: Transaction not accepted: 418987173499205375 transaction: {"type":0,"subtype":0,"timestamp":165423139,"deadline":1440,"senderPublicKey":"b087915478ba8f3e53400f05ca73cf99ae36865a08f22cfd47de7b526ee0fe5b","recipient":"2945594293674691670","amountNQT":2904063250001,"feeNQT":36750000,"ecBlockHeight":683976,"ecBlockId":"8103454603351769933","cashBackId":"0","signature":"44160a321f5c30612d9032dec10bee9660f80c546495d230209d2744fd47fa01e40d3e0782fc787d01c16540f8bdcd1934235830358b89d14f33b528b4a892dd","attachment":{},"version":1}
[INFO] 2024-07-25 00:19:37 brs.peer.PeerImpl - Blacklisting 89.135.65.122 (v3.8.2) because of: found invalid pull/push data during importing the block
[WARNING] 2024-07-25 00:19:37 brs.BlockchainProcessorImpl - Auto popping off as failed to push block
[WARNING] 2024-07-25 00:19:37 brs.BlockchainProcessorImpl - Popping off 36 blocks due to previous failures to push this block
[INFO] 2024-07-25 00:19:37 brs.BlockchainProcessorImpl - Rollback from 683989 to 683953
[WARNING] 2024-07-25 00:19:37 brs.BlockchainProcessorImpl - Block height 683953, total mined 207571387600000000, total effective+burnt 207571387599981685
```

I tried sync with H2 DB and it worked on this PC without any issue, node was synced after two days. Then I modified configuration and started the same with SQLite DB and it fails...

**Comment by flop01** [comment]
After some debugging with the community on discord, the root cause of this bug was pinpointed to very big queries that exceed SQLite's maximum character length for a query. Many thanks to everyone who helped !

Balances changes on block height 671802 were generating a single INSERT statement with 19072 rows, which were not inserted because the query was too big, resulting in the dabatase being corrupt, causing in turn the errors referenced in this issue.

A bugfix is proposed in pull request #840

**Comment by flop01** [comment]
For clarity: this fixes the deathloop of errors when syncing from genesis block with SQLite backend, that many people are reporting on discord
