### ISSUE TITLE
syntax error near 'fetch next 1 rows only'

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#826]
Node 3.8.1 running in Windows 11
MariaDB 10.5.23 running in GNU/Linux
Synchronizing from scratch

```
May 28, 2024 2:04:13 PM brs.Signum loadProperties
INFO: Initializing Signum Node version v3.8.1
May 28, 2024 2:04:13 PM brs.Signum loadProperties
INFO: Configurations from folder ./conf
May 28, 2024 2:04:13 PM brs.Signum loadProperties
INFO: Custom user properties file node.properties not loaded
May 28, 2024 2:04:13 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-05-28 14:04:15 brs.db.sql.Db - Using SQL Backend with Dialect MariaDB - Version 10.5.23-MariaDB-log
[INFO] 2024-05-28 14:04:15 brs.db.sql.Db - Running flyway migration
[SEVERE] 2024-05-28 14:04:23 brs.Signum - SQL [select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`alias_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows only]; (conn=11288) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
org.jooq.exception.DataAccessException: SQL [select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`alias_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows only]; (conn=11288) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
	at org.jooq_3.16.23.MARIADB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3130)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at brs.db.sql.EntitySqlTable.get(EntitySqlTable.java:152)
	at brs.db.sql.EntitySqlTable.lambda$getBy$2(EntitySqlTable.java:119)
	at brs.db.sql.Db.useDSLContext(Db.java:128)
	at brs.db.sql.EntitySqlTable.getBy(EntitySqlTable.java:110)
	at brs.db.sql.SqlAliasStore.getTLD(SqlAliasStore.java:176)
	at brs.services.impl.AliasServiceImpl.addDefaultTLDs(AliasServiceImpl.java:68)
	at brs.Signum.loadWallet(Signum.java:281)
	at brs.Signum.init(Signum.java:219)
	at brs.Signum.main(Signum.java:200)
	at brs.SignumGUI.runBrs(SignumGUI.java:363)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: (conn=11288) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:378)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
	at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4408)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
	... 14 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'fetch next 1 rows only' at line 1
Query is: select `alias`.`db_id`, `alias`.`id`, `alias`.`account_id`, `alias`.`alias_name`, `alias`.`alias_name_lower`, `alias`.`alias_uri`, `alias`.`timestamp`, `alias`.`height`, `alias`.`latest`, `alias`.`tld` from `alias` where (`alias`.`alias_name_lower` = 'signum' and `alias`.`tld` is null and `alias`.`latest` = true) fetch next 1 rows only
java thread: Thread-0
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:233)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
	... 22 more
[SEVERE] 2024-05-28 14:04:23 brs.SignumGUI - Signum Quit unexpectedly! Exit code  1
Showing message: Signum Quit unexpectedly! Exit code 1
```

**Comment by ipr0310** [comment]
@josergc You must update mariaDB to `10.6` version
![image](https://github.com/signum-network/signum-node/assets/35440957/b5a6f962-0d68-4219-aa10-a1918db960ac)

https://github.com/signum-network/signum-node/blob/main/DB_SETUP_MARIADB.md
