### ISSUE TITLE
Cannot sync with network, H2 DB errors

### ISSUE THREAD

**Issue by PSLLSP** [signum-network/signum-node#833]
Signum node v3.8.2
Linux Ubuntu 18.04.6, amd64

```
$ java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu118.04, mixed mode, sharing)
```

Files in DB directory:
```
$ ls -ltr db/
total 8412340
-rw-rw-r-- 1 user user          0 May 15 10:16 signum.sqlite.db-wal
-rw-rw-r-- 1 user user 4933713920 May 15 10:16 signum.sqlite.db
-rw-rw-r-- 1 user user      32768 Aug  4 14:47 signum.sqlite.db-shm
-rw-rw-r-- 1 user user   80603446 Aug  5 01:46 signum-v2.trace.db.old
-rw-rw-r-- 1 user user   60739584 Aug  5 02:09 signum-v2.trace.db
drwxrwxr-x 5 user user       4096 Aug  6 23:34 ../
drwxrwxr-x 2 user user       4096 Aug  6 23:37 ./
-rw-rw-r-- 1 user user 3538817024 Aug  6 23:37 signum-v2.mv.db
```

I tried to sync from block 0, DB is the default H2. I did something similar a week ago but I used different computer with newer Linux, different Java and different location and that was working fine, no issue.

This older PC cannot (more powerful HW but older Linux) sync, I see many errors that are looping so fast that it impacts PC performance significantly.

This is the last error in the console:

```
[SEVERE] 2024-08-06 23:34:41 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into "block" ("id", "version", "timestamp", "previous
_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "gen
erator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_
signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (395908010777007930
5, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA
5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', 
X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5
', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79
F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601
439150068549891, 120128021759, null)]; Referential integrity constraint violation: "CONSTRAINT_597C: PUBL
IC.block FOREIGN KEY(previous_block_id) REFERENCES PUBLIC.block(id) (9084879412776540335)"; SQL statement
:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (3959080107770079305, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601439150068549891, 120128021759, null) [23506-224]
        at org.jooq_3.16.23.H2.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3130)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:138)
        at brs.db.sql.SqlBlockchainStore.lambda$addBlock$16(SqlBlockchainStore.java:376)
        at brs.db.sql.Db.useDSLContext(Db.java:132)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:375)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:906)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1145)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_597C: PUBLIC.block FOREIGN KEY(previous_block_id) REFERENCES PUBLIC.block(id) (9084879412776540335)"; SQL statement:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (3959080107770079305, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601439150068549891, 120128021759, null) [23506-224]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:520)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:311)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:252)
        at org.h2.table.Table.fireConstraints(Table.java:1200)
        at org.h2.table.Table.fireAfterRow(Table.java:1218)
        at org.h2.command.dml.Insert.insertRows(Insert.java:188)
        at org.h2.command.dml.Insert.update(Insert.java:135)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:256)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:428)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:961)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
        ... 15 more
org.jooq.exception.DataAccessException: SQL [insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (3959080107770079305, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601439150068549891, 120128021759, null)]; Referential integrity constraint violation: "CONSTRAINT_597C: PUBLIC.block FOREIGN KEY(previous_block_id) REFERENCES PUBLIC.block(id) (9084879412776540335)"; SQL statement:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (3959080107770079305, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601439150068549891, 120128021759, null) [23506-224]
        at org.jooq_3.16.23.H2.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3130)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:727)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:138)
        at brs.db.sql.SqlBlockchainStore.lambda$addBlock$16(SqlBlockchainStore.java:376)
        at brs.db.sql.Db.useDSLContext(Db.java:132)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:375)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:906)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:1145)
        at brs.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:696)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_597C: PUBLIC.block FOREIGN KEY(previous_block_id) REFERENCES PUBLIC.block(id) (9084879412776540335)"; SQL statement:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "total_fee_cash_back", "total_fee_burnt", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (3959080107770079305, 3, 177644076, 9084879412776540335, 5000000000, 26460000, 0, 0, 1672, X'7108F927E2C166B204725B2C71EB6DA5AB38C8D847B86572CD6F0A4C8243D34E', X'AF18CE31B1F9137ED40DCCEA958752F8F2007924E103A036D3F0C4F45FB5B7D1', X'0522B77028BD80B17F', 101256, 734539, X'1296D0219398B2027ECC8CEB86691D306D2BA3367CFEF9D0DE75E60B4690BFB5', X'549BBE4D49CF2AE8F937B24730C27656E1940DCAFB4CC1D2512C16DE9658580AD68922AF2EE4380C9EA7082FC2003C415A79F3DCCA88C9712B987887D0912E14', X'C12FFBCBE79CE7E27B0AB2E3A24EB8C36AE8D10533A2E2AB1D06922A388CACDF', -8601439150068549891, 120128021759, null) [23506-224]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:520)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:311)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:252)
        at org.h2.table.Table.fireConstraints(Table.java:1200)
        at org.h2.table.Table.fireAfterRow(Table.java:1218)
        at org.h2.command.dml.Insert.insertRows(Insert.java:188)
        at org.h2.command.dml.Insert.update(Insert.java:135)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:256)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:428)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:961)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:329)
        ... 15 more
``` 

I restarted node:

```
Aug 06, 2024 11:54:48 PM signum.Launcher main
INFO: Running in headless mode as specified by argument
Aug 06, 2024 11:54:48 PM brs.Signum loadProperties
INFO: Initializing Signum Node version v3.8.2
Aug 06, 2024 11:54:48 PM brs.Signum loadProperties
INFO: Configurations from folder ./conf
Aug 06, 2024 11:54:48 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2024-08-06 23:54:51 brs.db.sql.Db - Using SQL Backend with Dialect H2 - Version 2.2.224
[INFO] 2024-08-06 23:54:51 brs.db.sql.Db - Running flyway migration
[INFO] 2024-08-06 23:54:52 brs.BlockchainProcessorImpl - Genesis block already in database
[INFO] 2024-08-06 23:54:52 brs.BlockchainProcessorImpl - Last block height: 734529, baseTarget: 93531
[INFO] 2024-08-06 23:54:55 brs.peer.Peers - P2P max connections: 20
...
[INFO] 2024-08-07 00:17:02 brs.statistics.StatisticsManagerImpl - handling 31.25 blocks/s account_balance cache hit ratio now/total:99.87%/98.69% account cache hit ratio now/total:99.82%/98.94%
[INFO] 2024-08-07 00:17:19 brs.BlockchainProcessorImpl - processed block 770000
[INFO] 2024-08-07 00:17:19 brs.statistics.StatisticsManagerImpl - handling 29.41 blocks/s account_balance cache hit ratio now/total:99.89%/98.71% account cache hit ratio now/total:99.77%/98.95%
...
```

**Comment by frankTheTank72** [comment]
Can you try with SQLite please.. 
H2 is no longer our default DB

**Comment by PSLLSP** [comment]
> Can you try with SQLite please.. H2 is no longer our default DB

Well, I have other issue that SQLite doesn't work at all. I tried SQLite on this machine few weeks ago and it was not working; I think it was v3.8.1 (May 15).

I was surprised that sync with H2 failed because a week ago it was working on different PC without issue. Could be this issue related to some rounding error? Or is CPU speed important? Is it issue related to CPU architecture (Intel i3 x AMD Ryzen)? Is it related to version of Java? Or is version of Linux important?

I restarted sync, it was running for several hours and sync process is locked again, on similar error.

**Comment by PSLLSP** [comment]
> Can you try with SQLite please..
> H2 is no longer our default DB

I installed signum-node v3.8.2 on new PC. I used default configuration, I have not modified any files in conf directory and  when I started, I see that default DB is H2, not SQLite...

When backend DB is configured as SQLite, I see a message that SQLite support is EXPERIMENTAL...

```
[INFO] 2024-08-07 08:13:38 brs.db.sql.Db - Using SQL Backend with Dialect SQLite - Version 3.45.2 (EXPERIMENTAL)
```

**Comment by frankTheTank72** [comment]
The DB locking is okay ... a normal warning
